version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ../:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ../:/var/www
            - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
